#ifndef NO_UINT_TYPEDEFS
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;
#define NO_UINT_TYPEDEFS  1
#endif

#define MCF_USB_OTG_ENDPT(x) ENDPT_ARR[4*(x)]
#define MCF_USB_OTG_ENDPT_EP_HSHK ENDPT0_EP_HSHK_MASK
#define MCF_USB_OTG_ENDPT_EP_RX_EN ENDPT0_EP_RX_EN_MASK
#define MCF_USB_OTG_ENDPT_EP_TX_EN ENDPT0_EP_TX_EN_MASK
#define MCF_USB_OTG_ENDPT_HOST_WO_HUB ENDPT0_HOST_WO_HUB_MASK
#define MCF_USB_OTG_ENDPT_RETRY_DIS ENDPT0_RETRY_DIS_MASK
#define MCF_USB_OTG_USB_CTRL_CLK_SRC(x)  (x)

#define MCF_CFM_CFMCLKD  FCDIV
#define MCF_CFM_CFMCLKD_DIVLD  FCDIV_FDIVLD_MASK
#define MCF_CFM_CFMUSTAT  FSTAT
#define MCF_CFM_CFMUSTAT_CBEIF  FSTAT_FCBEF_MASK
#define MCF_CFM_CFMUSTAT_PVIOL  FSTAT_FPVIOL_MASK
#define MCF_CFM_CFMUSTAT_ACCERR  FSTAT_FACCERR_MASK
#define MCF_CFM_CFMCMD  FCMD
#define MCF_CFM_CFMUSTAT_CCIF  FSTAT_FCCF_MASK
#define MCF_CFM_CFMCLKD_PRDIV8  FCDIV_PRDIV8_MASK
#define MCF_CFM_CFMCLKD_DIV(x)  (x)

#define MCF_CFM_CFMCMD_PAGE_ERASE  0x40
#define MCF_CFM_CFMCMD_WORD_PROGRAM  0x20

#define MCF_USB_OTG_TOKEN_TOKEN_PID(x)  ((x)<<4)
#define MCF_USB_OTG_TOKEN_TOKEN_ENDPT(x)  (x)

// automatic below

#define MCF_USB_OTG_ADDR ADDR
#define MCF_USB_OTG_ADDR_LS_EN ADDR_LS_EN_MASK
#define MCF_USB_OTG_BDT_PAGE_01 BDT_PAGE_01
#define MCF_USB_OTG_BDT_PAGE_02 BDT_PAGE_02
#define MCF_USB_OTG_BDT_PAGE_03 BDT_PAGE_03
#define MCF_USB_OTG_CTL CTL
#define MCF_USB_OTG_CTL_HOST_MODE_EN CTL_HOST_MODE_EN_MASK
#define MCF_USB_OTG_CTL_JSTATE CTL_JSTATE_MASK
#define MCF_USB_OTG_CTL_ODD_RST CTL_ODD_RST_MASK
#define MCF_USB_OTG_CTL_RESET CTL_RESET_MASK
#define MCF_USB_OTG_CTL_TXSUSPEND_TOKENBUSY CTL_TXSUSPEND_TOKENBUSY_MASK
#define MCF_USB_OTG_CTL_USB_EN_SOF_EN CTL_USB_EN_SOF_EN_MASK
#define MCF_USB_OTG_ENDPT0 ENDPT0
#define MCF_USB_OTG_INT_ENB INT_ENB
#define MCF_USB_OTG_INT_ENB_ATTACH_EN INT_ENB_ATTACH_EN_MASK
#define MCF_USB_OTG_INT_ENB_SLEEP_EN INT_ENB_SLEEP_EN_MASK
#define MCF_USB_OTG_INT_ENB_TOK_DNE_EN INT_ENB_TOK_DNE_EN_MASK
#define MCF_USB_OTG_INT_ENB_USB_RST_EN INT_ENB_USB_RST_EN_MASK
#define MCF_USB_OTG_INT_STAT INT_STAT
#define MCF_USB_OTG_INT_STAT_ATTACH INT_STAT_ATTACH_MASK
#define MCF_USB_OTG_INT_STAT_ERROR INT_STAT_ERROR_MASK
#define MCF_USB_OTG_INT_STAT_RESUME INT_STAT_RESUME_MASK
#define MCF_USB_OTG_INT_STAT_SLEEP INT_STAT_SLEEP_MASK
#define MCF_USB_OTG_INT_STAT_STALL INT_STAT_STALL_MASK
#define MCF_USB_OTG_INT_STAT_TOK_DNE INT_STAT_TOK_DNE_MASK
#define MCF_USB_OTG_INT_STAT_USB_RST INT_STAT_USB_RST_MASK
#define MCF_USB_OTG_OTG_CTRL OTG_CTRL
#define MCF_USB_OTG_OTG_CTRL_DM_LOW OTG_CTRL_DM_LOW_MASK
#define MCF_USB_OTG_OTG_CTRL_DP_HIGH OTG_CTRL_DP_HIGH_MASK
#define MCF_USB_OTG_OTG_CTRL_DP_LOW OTG_CTRL_DP_LOW_MASK
#define MCF_USB_OTG_OTG_CTRL_OTG_EN OTG_CTRL_OTG_EN_MASK
#define MCF_USB_OTG_SOF_THLD SOF_THLD
#define MCF_USB_OTG_STAT STAT
#define MCF_USB_OTG_STAT_ODD STAT_ODD_MASK
#define MCF_USB_OTG_STAT_TX STAT_TX_MASK
#define MCF_USB_OTG_TOKEN TOKEN
#define MCF_USB_OTG_USB_CTRL USB_CTRL
